version: '3.9'

services:
  web:
    container_name: fzsport-web
    restart: always
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - app
    links:
      - app
  app:
    container_name: fzsport-app
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
    # ports:
    #   - '3000:3000'
    links:
      - db
    volumes:
      - .:/usr/src/app   
    depends_on:
      - db
  db:
    container_name: fzsport-db
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    # ports:
    #   - '27017:27017'
    logging:
      driver: none
    volumes:
      - ./data/mongo:/data/db
    