GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/api/team HTTP/1.1

###
GET http://localhost:3000/api/teams/143/players HTTP/1.1

###
GET http://localhost:3000/api/teams/players/Arquero HTTP/1.1